# Generated by Django 4.1 on 2022-09-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('intro', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('image', models.FileField(blank=True, null=True, upload_to='static/imag/blog_post_image')),
                ('post_status', models.CharField(choices=[('PUB', 'PUBLISHED'), ('DRAF', 'DRAFT')], default='PUBLISHED', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
