# Generated by Django 4.1 on 2022-09-02 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_status',
            new_name='status',
        ),
    ]
