# Generated by Django 4.1 on 2022-09-03 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0008_alter_post_image_alter_post_intro_alter_post_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_at',)},
        ),
        migrations.RenameField(
            model_name='post',
            old_name='created_at',
            new_name='published_at',
        ),
    ]
