# Generated by Django 4.1 on 2022-09-04 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog', '0009_alter_post_options_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryModel',
        ),
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
    ]
